### ISSUE TITLE
Issue with source distribution submitted to PyPI

### ISSUE THREAD

**Issue by steven-cutting** [kurtbrose/fossil-delta#1]
## Error installing fossil-delta

When I run `pip install -r requirements.txt` for the carbonite project. I run into install issue with fossil-delta.  Pip seems to have trouble 

The third approach (below) works, but is just a work around. 

Based on looking at the setup.py file for fossil-delta and the artifact submitted to PyPI, it looks like not all of the source files are being included

### My sys info
OS: OSX
Python version: 3.6.5
pip version: 10.0.1

### Trying to install from PyPI

```bash
$ env pip install fossil-delta
```

```
Collecting fossil-delta
  Using cached https://files.pythonhosted.org/packages/62/e1/a33de916fdb16bacf31a642cf1092cfaddcab9608718e37acb326ce6c22c/fossil-delta-17.12.0.tar.gz
Installing collected packages: fossil-delta
  Running setup.py install for fossil-delta ... error
    Complete output from command /Users/stevencutting/projects/carbonite/env-carbonite/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/yg/bdg2p64j0fzbqvlc53vjcqz80000gn/T/pip-install-srimfsau/fossil-delta/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/yg/bdg2p64j0fzbqvlc53vjcqz80000gn/T/pip-record-a3q69rht/install-record.txt --single-version-externally-managed --compile --install-headers /Users/stevencutting/projects/carbonite/env-carbonite/include/site/python3.6/fossil-delta:
    running install
    running build
    running build_ext
    building 'fossil_delta' extension
    creating build
    creating build/temp.macosx-10.13-x86_64-3.6
    creating build/temp.macosx-10.13-x86_64-3.6/src
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/Users/stevencutting/projects/carbonite/env-carbonite/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/fossil_delta.c -o build/temp.macosx-10.13-x86_64-3.6/src/fossil_delta.o
    src/fossil_delta.c:523:10: fatal error: 'alloc_map.h' file not found
    #include "alloc_map.h"
             ^~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/Users/stevencutting/projects/carbonite/env-carbonite/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/yg/bdg2p64j0fzbqvlc53vjcqz80000gn/T/pip-install-srimfsau/fossil-delta/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/yg/bdg2p64j0fzbqvlc53vjcqz80000gn/T/pip-record-a3q69rht/install-record.txt --single-version-externally-managed --compile --install-headers /Users/stevencutting/projects/carbonite/env-carbonite/include/site/python3.6/fossil-delta" failed with error code 1 in /private/var/folders/yg/bdg2p64j0fzbqvlc53vjcqz80000gn/T/pip-install-srimfsau/fossil-delta/
```

### Trying to install from PyPI with `USE_CYTHON` env set to 'true'

```bash
export USE_CYTHON="True"
```

```bash
$ echo $USE_CYTHON
True
```

```bash
$ env pip install fossil-delta
```

```
Collecting fossil-delta
  Using cached https://files.pythonhosted.org/packages/62/e1/a33de916fdb16bacf31a642cf1092cfaddcab9608718e37acb326ce6c22c/fossil-delta-17.12.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/yg/bdg2p64j0fzbqvlc53vjcqz80000gn/T/pip-install-8sgb0hti/fossil-delta/setup.py", line 13, in <module>
        extensions = cythonize(extensions)
      File "/Users/stevencutting/projects/carbonite/env-carbonite/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 897, in cythonize
        aliases=aliases)
      File "/Users/stevencutting/projects/carbonite/env-carbonite/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 777, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/stevencutting/projects/carbonite/env-carbonite/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 102, in nonempty
        raise ValueError(error_msg)
    ValueError: 'src/fossil_delta.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/yg/bdg2p64j0fzbqvlc53vjcqz80000gn/T/pip-install-8sgb0hti/fossil-delta/
```

### Work around

Clone `fossil-delta` from github. Run `pip install .` within the `fossil-delta` dir.

**Comment by steven-cutting** [comment]
I will try submitting a pull request that fixes this issue.
